name: kantongpintar
description: A new Flutter project.

# Versi SDK yang akan kita gunakan
environment:
  sdk: '>=3.3.0 <4.0.0'

# Daftar package yang kita butuhkan
dependencies:
  flutter:
    sdk: flutter

  # Package dari Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  
  # Package untuk grafik
  fl_chart: ^0.68.0
  
  # Package untuk state management
  provider: ^6.1.2

  # Package icon bawaan
  cupertino_icons: ^1.0.2

# Bagian ini adalah untuk settingan Flutter, jangan diubah
flutter:
  uses-material-design: true